In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv('data\Motor vehicle insurance data.csv',sep=';')

In [14]:
df

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105550,53498,30/07/2018,30/07/2018,30/07/2019,25/07/1981,14/02/2007,0,1,1,1,...,0,0,2000,110,1997,24320.00,5,D,4.740,1480
105551,53499,16/08/2018,16/08/2018,16/08/2019,08/12/1976,29/11/2017,0,1,1,1,...,0,0,2013,129,1998,30861.97,5,P,4.650,1440
105552,53500,21/11/2018,21/11/2018,21/11/2019,01/04/1974,05/10/2011,0,1,1,1,...,0,0,1999,55,999,7800.00,5,P,3.495,830
105553,53501,21/11/2018,21/11/2018,21/11/2019,15/09/1946,02/02/1982,0,1,1,1,...,0,0,2004,90,1753,16610.00,5,D,4.555,1399
105554,53502,01/10/2018,01/10/2018,01/10/2019,09/05/1973,30/09/1991,1,1,1,1,...,0,0,2010,140,1968,33400.00,5,D,4.854,1699

In [39]:
df = df.sort_values(["ID", "Date_start_contract"])

train_list = []
test_list = []

# prvo nađi unique ID-eve (gde je samo 1 red)
group_sizes = df.groupby("ID").size()
single_ids = group_sizes[group_sizes == 1].index

# random 20% tih ID-eva
np.random.seed(42)  # zbog reprodukcije
test_single_ids = np.random.choice(single_ids, 
                                   size=int(0.2 * len(single_ids)), 
                                   replace=False)

for id_val, group in df.groupby("ID"):
    if len(group) == 1:
        if id_val in test_single_ids:
            test_list.append(group)
        else:
            train_list.append(group)
    else:
        train_list.append(group.iloc[:-1])
        test_list.append(group.iloc[-1:])

train = pd.concat(train_list)
test = pd.concat(test_list)

In [40]:
train.to_csv("data/train.csv", index=False)
test.to_csv("data/test.csv", index=False)

In [37]:
test

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
5,2,26/09/2017,26/09/2018,26/09/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
9,3,29/11/2013,29/11/2018,29/11/2019,18/03/1975,10/07/1995,0,15,1,2,...,0,0,2013,85,1229,16030.00,5,P,3.999,1105
12,4,21/10/2016,21/10/2018,21/10/2019,10/07/1973,05/07/1993,0,3,2,2,...,0,0,1986,6,74,1261.82,0,P,NaN,87
14,5,12/05/2017,12/05/2018,12/05/2019,10/07/1973,05/07/1993,0,3,2,2,...,0,0,1986,6,244,3000.00,0,P,NaN,92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105525,53473,13/11/2018,13/11/2018,13/11/2019,22/05/1981,01/03/2014,1,1,1,1,...,1,0,2001,112,2184,18600.00,5,D,4.197,1298
105526,53474,05/10/2018,05/10/2018,05/10/2019,05/03/1985,26/04/2003,0,1,2,2,...,0,0,2002,170,2685,40823.11,4,D,4.818,1650
105529,53477,22/11/2018,22/11/2018,22/11/2019,10/09/1963,22/10/2014,1,1,1,1,...,0,0,2010,90,1560,19120.00,5,D,4.276,1228
105548,53496,11/09/2018,11/09/2018,11/09/2019,26/07/1984,28/04/2017,0,1,1,1,...,0,0,1998,11,505,10217.21,3,P,NaN,400
105553,53501,21/11/2018,21/11/2018,21/11/2019,15/09/1946,02/02/1982,0,1,1,1,...,0,0,2004,90,1753,16610.00,5,D,4.555,1399

In [18]:
df.columns

Index(['ID', 'Date_start_contract', 'Date_last_renewal', 'Date_next_renewal',
       'Date_birth', 'Date_driving_licence', 'Distribution_channel',
       'Seniority', 'Policies_in_force', 'Max_policies', 'Max_products',
       'Lapse', 'Date_lapse', 'Payment', 'Premium', 'Cost_claims_year',
       'N_claims_year', 'N_claims_history', 'R_Claims_history', 'Type_risk',
       'Area', 'Second_driver', 'Year_matriculation', 'Power',
       'Cylinder_capacity', 'Value_vehicle', 'N_doors', 'Type_fuel', 'Length',
       'Weight'],
      dtype='object')